project:
  type: website
  
resources:
  - plots/*

website:
  title: "AD688 Group 1 - Fall 2025"
  favicon: images/icon_group.png
  navbar:
    logo: images/icon_group.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research Background"
        href: research_introduction.qmd
      - text: Analysis
        menu:
          - text: "Industry and Location Salary Analysis"
            href: job_market_salary_analysis.ipynb
          - text: "Salary Linear Regression Model"
            href: linear_regression.ipynb
          - text: "Analysis #3"
            href: feidhelm_analysis.ipynb
      - text: "Career Plans"
        href: career_plan.qmd
      - text: "About Us"
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true