project:
  type: website

website:
  title: "AD688-GROUP1-F25"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "GitHub Repo"
        href: https://bdegouw.github.io/ad688-group1-job-market-analysis-f25/

format:
  html:
    theme: 
      - cosmo
      - brand
    css: styles.css
    toc: true




