project:
  type: website

website:
  title: "AD688-GROUP1-F25"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd


format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-location: right





