project:
  type: website

website:
  title: "AD688-GROUP1-F25"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Salary Analysis"
        href: job_market_salary_analysis.ipynb

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-location: right
    code-fold: false        # hide fold buttons
    code-tools: false       # no code copy/inspect icons
    code-block-bg: false
    code-block-border-left: false
    code: false             # <-- THIS hides all code globally






