---
title: "Meet the Team"
---

## Bowen de Gouw
- **Program**: MSc Applied Business Analytics, BU MET  
- **Background**: Briefly describe your academic/professional background (e.g., data analysis, business strategy).  
- **Interests**: Key interests related to this project (e.g., AI in finance, predictive analytics).  
- **Career Goals**: 1–2 sentences about future plans.  

---

## Feidhelm Joyce
- **Program**: MSc Applied Business Analytics, BU MET  
- **Background**: Graduate student in Applied Business Analytics at Boston University having graduated from Dublin City University with a bachelor's degree in Business Management in 2022. Experienced in Python, R, SQL, PySpark for data modeling, data engineering, applied analytics, statistical analysis, and cloud-based pipelines. Professional background spans financial analytics, client strategy, and fraud data analysis, blending technical insight with business decision-making across a range of companies from both the US & Ireland.  
- **Interests**: Focused on the intersection of machine learning, workforce analytics, and business intelligence. Research interests include predictive modeling, automation impacts on employment, cloud-based data engineering, and applied AI for strategic decision-making. Passionate about bridging the gap between quantitative analytics and organizational transformation through scalable data solutions. Hobbies away from the desk include Hurling, Gaelic Football, Soccer & Golf.
- **Career Goals**: Aspire to build a career as a data and analytics consultant or business intelligence strategist, leveraging data science and automation to guide evidence-based decisions in corporate and policy settings. 

---

## Mahnoor Khalid
- **Program**: MSc Applied Business Analytics, BU MET  
- **Background:** Experienced Digital Enablement Executive at Bayer (2021–2025), where I launched Pakistan’s first farmer-focused digital platform, scaled loyalty programs, and drove digital transformation initiatives. Previously, Supply Chain Associate at Nestlé, optimizing efficiency and vendor processes.  
- **Interests:** Data analytics, cloud technologies, digital transformation, sustainability in supply chains, as well as swimming, cooking, and sports.  
- **Career Goals:** Aspire to leverage analytics and digital transformation expertise to drive innovation in global business environments, integrating technology and strategy for measurable impact.  

---


