---
title: "Research Introduction: AI vs. Non-AI Careers"
author: "Team 1"
date: today
format: 
  html:
    bibliography: references.bib
    csl: csl/econometrica.csl
    toc: true
---
## Background Research
---

## NEED TO ADD REFERENCES ONTO THE REFERENCES PAGE

- The research study “From Junior to Senior: Skill Requirements for AI Professionals Across Career Stages”, provides clear context for understanding salary and compensation trends in AI careers. The study analyzed nearly 19,000 LinkedIn job postings, in which it showed that senior AI roles dominated the market with 67.4% of AI postings. Demand for these jobs not only included technical expertise in Python, AWS and deep learning, but commanded a high demand for leadership, communication, and strategic skills, which all lead to higher compensation. In contrast, the junior AI positions emphasised the importance of foundational technical skillsets, including Python, SQL, and machine learning, reflecting the lower entry-level pay, but a strong potential for career growth. The findings for the research also suggested that in 2024, industries that invested heavily in AI, such as Technology, Finance and Healthcare, likely experienced the largest wage growth, as they seek AI professionals who can bridge their technical skillset with innovation. The research rationale lies in the understanding of how skill specialization and AI literacy directly enhance employability and salary prospects. It focuses on how crucial it is for new entrants to identify which skills and career path yields the highest returns. 

- The article: “The Future of Work: Impacts of AI on Employment and Job Market Dynamics” examines how artificial intelligence (AI) is transforming employment by simultaneously displacing traditional roles and creating new opportunities across industries. Drawing from leading studies and empirical research, it highlights that automation will impact up to half of current work activities, particularly routine and manual jobs, while generating emerging roles in AI development, data analysis, and system maintenance. The authors argue that successful adaptation requires proactive reskilling, upskilling, and curriculum reform, emphasizing human capabilities such as creativity, critical thinking, and emotional intelligence. They propose coordinated strategies involving policymakers, educators, and employers to establish ethical AI governance, workforce training incentives, and public-private partnerships. Through sector-specific analyses - from manufacturing to healthcare and finance - the study concludes that AI’s impact on labor is not purely destructive but transformative, enabling a more collaborative human-machine workforce that supports innovation, productivity, and long-term economic growth.
- test
